# Generated by Django 4.2.5 on 2023-12-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('identification', models.CharField(max_length=100)),
                ('facial', models.ImageField(upload_to='facial_scan/')),
            ],
        ),
    ]
